name: build-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build, Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: mkdir _build
      - uses: xu-cheng/latex-action@v2
        with:
          working_directory: latex
          #args: -output-directory ../_build
          root_file: ManasTalukdar.tex
      - uses: xu-cheng/latex-action@v2
        with:
          working_directory: latex
          #args: -output-directory ../_build
          root_file: ManasTalukdar_cv.tex
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: node --version
      - working-directory: website
        run: npm install
      - working-directory: website
        run: cp ../latex/*.pdf ./public/resources/
      - working-directory: website
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          publish_branch:  gh-pages  # default: gh-pages
          keep_files: false # default: false
          force_orphan: true
          commit_message: "GitHub CI Updates [ci skip]"