name: build-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build, Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Extract Branch Name
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - run: mkdir _build
      - uses: xu-cheng/latex-action@v4
        with:
          working_directory: latex
          #args: -output-directory ../_build
          root_file: ManasTalukdar.tex
      - uses: xu-cheng/latex-action@v4
        with:
          working_directory: latex
          #args: -output-directory ../_build
          root_file: ManasTalukdar_cv.tex
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: node --version
      - working-directory: website
        run: npm install
      - working-directory: website
        run: cp ../latex/*.pdf ./public/resources/
      - working-directory: website
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && env.BRANCH == 'main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist
          publish_branch:  gh-pages  # default: gh-pages
          keep_files: false # default: false
          force_orphan: true
          commit_message: "GitHub CI Updates [ci skip]"